packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^3.12.1
  '@nuxt/devtools': ^1.7.0
  '@nuxt/eslint-config': ^0.7.4
  '@nuxt/kit': ^3.15.0
  '@nuxt/module-builder': ^0.8.4
  '@nuxt/schema': ^3.15.0
  '@nuxt/test-utils': ^3.15.1
  '@types/node': latest
  '@vitest/coverage-v8': ^2.1.8
  automd: ^0.3.12
  bumpp: ^9.9.2
  changelogen: ^0.5.7
  eslint: ^9.17.0
  jiti: ^2.4.2
  lint-staged: ^15.3.0
  nuxt: ^3.15.0
  rimraf: ^6.0.1
  simple-git-hooks: ^2.11.1
  typescript: ~5.6.3
  unbuild: ^3.2.0
  vite: ^6.0.6
  vitest: ^2.1.8
  vue-tsc: ^2.2.0
